#!/usr/bin/env python3
"""
MoodMend Production Setup Script
Sets up the production environment for Docker deployment.
"""

import os
import secrets
import subprocess
import sys
from pathlib import Path

def generate_secret_key():
    return secrets.token_hex(32)

def setup_production():
    print("🚀 Starting MoodMend Production Setup...")
    
    # 1. Create necessary directories
    directories = ['data', 'backups']
    for directory in directories:
        Path(directory).mkdir(exist_ok=True)
        print(f"✅ Created directory: {directory}/")
        # In a real production environment, you might want to set specific permissions here
        # os.chmod(directory, 0o700) 

    # 2. Check/Create .env file
    env_file = Path('.env')
    if not env_file.exists():
        print("⚠️  .env file not found. Generating a secure production .env file...")
        secret_key = generate_secret_key()
        
        env_content = f"""# MoodMend Production Configuration
# Generated by setup_production.py

# Server (Railway usually provides PORT automatically)
PORT=${PORT:-3000}
HOST=0.0.0.0
DEBUG=False

# Database
DATABASE_PATH=/app/data/moodmend.db
DATABASE_BACKUP_PATH=/app/backups
LOG_FILE=/app/data/moodmend.log

# Security
SECRET_KEY={secret_key}
BCRYPT_ROUNDS=12

# CORS (Restrict this in production!)
CORS_ORIGINS=*
"""
        with open(env_file, 'w') as f:
            f.write(env_content)
        print(f"✅ Generated .env file with new SECRET_KEY.")
    else:
        print("✅ .env file already exists. Skipping generation.")

    # 3. Check for Docker
    try:
        subprocess.run(['docker', '--version'], check=True, stdout=subprocess.DEVNULL)
        print("✅ Docker is installed.")
    except (subprocess.CalledProcessError, FileNotFoundError):
        print("❌ Docker is NOT installed or not in PATH. Please install Docker first.")
        sys.exit(1)

    # 4. Build and Run via Docker Compose
    print("\n📦 Building and starting MoodMend container...")
    try:
        subprocess.run(['docker-compose', 'up', '-d', '--build'], check=True)
        print("\n✅ MoodMend is running!")
        print("👉 Access the app at http://localhost:3000")
        print("👉 Health check: http://localhost:3000/health")
        print("\n⚠️  Note: If this is the first run, the database will be created automatically in ./data/")
    except subprocess.CalledProcessError:
        print("\n❌ Failed to start Docker container. Check the logs above.")
        sys.exit(1)

if __name__ == '__main__':
    setup_production()
